# Generated by Django 3.2 on 2021-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('cat_status', models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], default='BLOCK', max_length=30)),
            ],
        ),
    ]
