# Generated by Django 3.2 on 2021-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categoryint',
            field=models.IntegerField(default=0),
        ),
    ]
