# Generated by Django 3.2 on 2021-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_subcategory_categoryint'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcat_status',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], default='BLOCK', max_length=30),
        ),
    ]
