# Generated by Django 3.2 on 2021-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_subcategory_subcat_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=60)),
                ('productprice', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discountprice', models.IntegerField(default=0)),
                ('productimage', models.ImageField(blank=True, null=True, upload_to='product/images')),
            ],
        ),
    ]
