# Generated by Django 3.2 on 2021-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proddiscription',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
