# Generated by Django 3.2 on 2021-05-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_proddiscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoryindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategoryindex',
            field=models.IntegerField(default=0),
        ),
    ]
