# Generated by Django 3.2 on 2021-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20210518_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_status',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], default='BLOCK', max_length=30),
        ),
    ]
