# Generated by Django 3.2 on 2021-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_auto_20210601_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
