# Generated by Django 3.2 on 2021-06-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_userdata_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
