# Generated by Django 3.2 on 2021-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
